FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose Vite port
EXPOSE 5173

# Run dev server with host flag to be accessible outside container
CMD ["npm", "run", "dev", "--", "--host"]
